name: Build And Push Docker Image

on:
  push:
    branches:
      - master
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build-and-push-docker-image
      with:
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
